hbase:
  zookeeper:
    quorum: 192.168.1.201,192.168.1.202,192.168.1.203
    port: 2181

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) [%40.40file:%-5.5line] - %black(%msg%n)"